cmake_minimum_required(VERSION 2.8.5)

# Declare the version of HEP Tools we use
# (must be done before including heptools-common to allow evolution of the
# structure)
set(heptools_version  dev3)

include(${CMAKE_CURRENT_LIST_DIR}/heptools-common.cmake)

# please keep alphabetic order and the structure (tabbing).
# it makes it much easier to edit/read this file!


# Application Area Projects
LCG_AA_project(ROOT  v6.12.06)
LCG_AA_project(Geant4 10.04.p01)
LCG_AA_project(HepMC 2.06.09)

# Externals

# ROOT Dependencies
LCG_external_package(Python            2.7.14                                   )
LCG_external_package(fftw              3.3.4                     fftw3          )
LCG_external_package(graphviz          2.28.0                                   )
LCG_external_package(GSL               2.4                                      )
LCG_external_package(mysql             5.7.20                                   )
LCG_external_package(xrootd            4.8.2                                    )
LCG_external_package(numpy             1.14.2                                   )
LCG_external_package(tbb               2018_U1                              )
LCG_external_package(blas              3.8.0                                    )
LCG_external_package(zlib              1.2.11                                   )
LCG_external_package(libxml2           2.9.7                                    )
if(NOT ${LCG_OS} STREQUAL mac)
  LCG_external_package(Davix             0.6.7                                    )
endif()
LCG_external_package(R                 3.2.5                                    )
LCG_external_package(oracle            11.2.0.3.0                               )
LCG_external_package(Vc                1.3.2                                    )

# Root binary Dependencies
#---EMI-2 grid externals and other binary packages---------------------
if(NOT ${LCG_OS} MATCHES mac)
  LCG_external_package(libunwind       5c2cade                                  )
  LCG_external_package(igprof          5.9.16                                   )
endif()
if(${LCG_OS} STREQUAL slc OR ${LCG_OS} STREQUAL centos)
  if (NOT ${LCG_HOST_ARCH} STREQUAL i686)
   LCG_external_package(CASTOR          2.1.13-6               castor            )
   LCG_external_package(cream           1.14.0-4               Grid/cream        )
   LCG_external_package(dcap            2.47.7-1               Grid/dcap         )
   LCG_external_package(dm-util         1.15.0-0               Grid/dm-util      )
   LCG_external_package(dpm             1.8.5-1                Grid/DPM          )
   LCG_external_package(epel            20130408               Grid/epel         )
   LCG_external_package(FTS             2.2.8emi2              Grid/FTS          )
   if(${LCG_OS}${LCG_OSVERS} STREQUAL slc6)
    LCG_external_package(FTS3           0.0.1-88               Grid/FTS3         )
   endif()
   LCG_external_package(gfal            1.13.0-0               Grid/gfal         )
##   LCG_external_package(gfal2           2.2.0-1                Grid/gfal2        )
   LCG_external_package(gridftp_ifce    2.3.1-0                Grid/gridftp-ifce )
   LCG_external_package(gridsite        1.7.25-1.emi2          Grid/gridsite     )
   LCG_external_package(is_ifce         1.15.0-0               Grid/is-ifce      )
   LCG_external_package(lb              3.2.9                  Grid/lb           )
   LCG_external_package(lcgdmcommon     1.8.5-1                Grid/lcg-dm-common)
   LCG_external_package(lcginfosites    3.1.0-3                Grid/lcg-infosites)
   LCG_external_package(lfc             1.8.5-1                Grid/LFC          )
   LCG_external_package(srm_ifce        1.13.0-0               Grid/srm-ifce     )
   LCG_external_package(voms            2.0.9-1                Grid/voms         )
   LCG_external_package(WMS             3.4.0                  Grid/WMS          )
   LCG_external_package(neurobayes        3.7.0                                  )
   LCG_external_package(neurobayes_expert 3.7.0                                  )
  endif()
endif()


# Geant4 Dependencies
LCG_external_package(Qt5               5.9.2                    qt5             )
LCG_external_package(XercesC           3.1.4                    author=3.1.4    )
LCG_external_package(CLHEP             2.4.0.1                  clhep           )
LCG_external_package(VecGeom           v00.05.01                                )
LCG_external_package(expat             2.2.5                                    )

# Boost
LCG_external_package(Boost             1.65.0                                   )

# xerces-c Dependencies
if(${LCG_OS}${LCG_OSVERS} STREQUAL slc6)
  LCG_external_package(curl              7.19.7                                 )
else()
  LCG_external_package(curl              7.59.0                                   )
endif()

# Qt5 Dependencies
if (NOT (${LCG_OS} STREQUAL ubuntu ))
  LCG_external_package(libxkbcommon      0.7.1                                    )
endif()
LCG_external_package(glib              2.52.2                                    )

# numpy Dependencies
LCG_external_package(setuptools        36.0.1                                   )

# graphviz Dependencies
LCG_external_package(libtool           2.4.2                                    )
LCG_external_package(pango             1.40.13                                  )
LCG_external_package(fontconfig        2.12.6                                   )

# Python Dependencies
LCG_external_package(sqlite            3210000                                  )
if(${LCG_OS} MATCHES mac)
    LCG_external_package(openssl           1.0.2d                                   )
endif()

# glib Dependencies
LCG_external_package(libffi            3.2.1                                )
LCG_external_package(pcre              8.38                                     )
LCG_external_package(pkg_config        0.28                                     )

# pango Dependencies
LCG_external_package(cairo             1.15.8                                   )
LCG_external_package(harfbuzz          1.6.3                                    )
LCG_external_package(freetype          2.6.3                                    )

# fontconfig Dependencies
LCG_external_package(gperf             3.1                                      )

# cairo Dependencies
LCG_external_package(png               1.6.17                                   )
LCG_external_package(pixman            0.34.0                                    )

# R Dependencies
LCG_external_package(zeromq            4.1.6                                    )

# VecGeom Dependencies
LCG_external_package(veccore           0.4.2                                      )
LCG_external_package(umesimd           0.8.1                                     )

LCG_external_package(cython            0.27.3                                   )

# MonteCarlo Generators
LCG_external_package(lhapdf            5.9.1          ${MCGENPATH}/lhapdf       )
LCG_external_package(lhapdfsets        5.9.1          lhapdfsets   )

LCG_external_package(lhapdf            6.1.5          ${MCGENPATH}/lhapdf       )
LCG_external_package(lhapdf            6.1.5.cxxstd   ${MCGENPATH}/lhapdf author=6.1.5 usecxxstd=1 )
LCG_external_package(lhapdf            6.1.6          ${MCGENPATH}/lhapdf       )
LCG_external_package(lhapdf            6.1.6.cxxstd   ${MCGENPATH}/lhapdf author=6.1.6 usecxxstd=1 )
LCG_external_package(lhapdf            6.2.0          ${MCGENPATH}/lhapdf       )
LCG_external_package(lhapdf            6.2.1          ${MCGENPATH}/lhapdf       )

LCG_external_package(pythia8           210            ${MCGENPATH}/pythia8 )
LCG_external_package(pythia8           223            ${MCGENPATH}/pythia8 )
LCG_external_package(pythia8           219            ${MCGENPATH}/pythia8 author=219 )
LCG_external_package(pythia8           219.pdf6plugin ${MCGENPATH}/pythia8 author=219 lhapdf6plugin=LHAPDF6.h )
LCG_external_package(pythia8           230            ${MCGENPATH}/pythia8 )
LCG_external_package(pythia8           235            ${MCGENPATH}/pythia8 )

LCG_external_package(pythia6           427.2          ${MCGENPATH}/pythia6    author=6.4.27 hepevt=10000  )
LCG_external_package(pythia6           428.2          ${MCGENPATH}/pythia6    author=6.4.28 hepevt=10000  )
LCG_external_package(pythia6           429.2          ${MCGENPATH}/pythia6    author=6.4.28 hepevt=10000  )


#
#
# LCG_external_package(lcgenv            1.3.5                                    )
# LCG_external_package(hepmc3            3.0.0                                    )
# LCG_external_package(4suite            1.0.2p1                                  )
# LCG_external_package(absl_py           0.2.0                                      )
# LCG_external_package(AIDA              3.2.1                                    )
# LCG_external_package(arrow             0.8.0                                    )
# LCG_external_package(pyarrow           0.8.0                                    )
# LCG_external_package(astroid           1.6.4                                    )
# LCG_external_package(autoconf          2.69                                     )
# LCG_external_package(automake          1.14                                     )
# LCG_external_package(backports         1.0.0                                    )
# LCG_external_package(backports.ssl_match_hostname       3.4.0.2                 )
# LCG_external_package(backports.shutil_get_terminal_size 1.0.0                   )
# LCG_external_package(backports.lzma    0.0.6                                    )
# LCG_external_package(backports.functools_lru_cache      1.4                     )
# LCG_external_package(benchmark         1.4.0                                    )
# LCG_external_package(backports_abc     0.5                                      )
# LCG_external_package(bleach            2.0.0                                    )
# LCG_external_package(C50               2.07                                     )
# if(NOT LCG_COMP STREQUAL "clang")
# LCG_external_package(catboost          0.5                                   )
# endif()
# LCG_external_package(certifi           14.05.14                                 )
# LCG_external_package(click             6.7                                      )
# LCG_external_package(cloudpickle       0.5.3                                    )
# LCG_external_package(cmmnbuild         2.1.3                                    )
# LCG_external_package(configparser      3.5.0                                    )
# LCG_external_package(cppgsl            b07383ea                                 )
# LCG_external_package(cycler            0.10.0                                   )
# LCG_external_package(decorator         4.0.9                                    )
# LCG_external_package(delphes           3.4.2pre12                                    )
# LCG_external_package(dill              0.2.5                                    )
# LCG_external_package(distributed       1.21.8                                   )
# LCG_external_package(joblib            0.10.0                                   )
# LCG_external_package(jsonc             0.12                                     )
# LCG_external_package(jsoncpp           1.7.2                                    )
# LCG_external_package(ccache            3.3.4                                    )
# LCG_external_package(chardet           3.0.4                                    )
# LCG_external_package(clang             3.9.0                                    )
# LCG_external_package(CouchDB           1.0.1                                    )
# LCG_external_package(cmaketools        1.6                                      )
# LCG_external_package(CMake             3.11.1                                   )
# LCG_external_package(cmt               v1r20p20090520                           )
# LCG_external_package(coin3d            3.1.3p2                                  )
# LCG_external_package(coverage          4.4.1                                    )
# LCG_external_package(CppUnit           1.12.1_p1                 author=1.12.1  )
# LCG_external_package(cx_oracle         5.1.1                                    )
#
# LCG_external_package(dask              0.17.5                                   )
#
# LCG_external_package(Django            1.9.12                                   )
# LCG_external_package(doxygen           1.8.11                                   )
# LCG_external_package(eigen             3.2.9                                    )
# LCG_external_package(elasticsearch     6.2.0                                    )
# LCG_external_package(entrypoints       0.2.2                                    )
# LCG_external_package(enum34            1.1.6                                    )
# LCG_external_package(fastjet           3.3.0                                    )
# LCG_external_package(flatbuffers       1.8.0                                    )
# LCG_external_package(fjcontrib         1.030                                    )
# LCG_external_package(fplll             5.0.3                                    )
# LCG_external_package(Frontier_Client   2.8.19                     frontier_client)
# LCG_external_package(ftjam             2.5.2                                    )
# LCG_external_package(funcsigs          1.0.2                                    )
# LCG_external_package(future            0.16.0                                   )
# LCG_external_package(futures           3.0.5                                    )
# #LCG_external_package(GCCXML            0.9.0_20131026            gccxml         )
# LCG_external_package(gast              0.2.0                                      )
# if(NOT ${LCG_OS} MATCHES mac)
#   LCG_external_package(gdb               7.12.1                                    )
# endif()
# LCG_external_package(genshi            0.7                                      )
# LCG_external_package(gettext           0.19.8.1                                 )
# LCG_external_package(gmp               6.0.0                                    )
# LCG_external_package(gnuplot           5.0.6                                    )
# if(${LCG_OS} STREQUAL slc OR ${LCG_OS} STREQUAL centos OR ${LCG_OS} STREQUAL cc)
# LCG_external_package(go                1.9.2                                    )
# LCG_external_package(gophernotes       1.0.0-rc1                                )
# endif()
# if(NOT LCG_COMP STREQUAL "clang")
#   LCG_external_package(gperftools	       2.5                                      )
# endif()
# LCG_external_package(gtest             master20160308                           )
# LCG_external_package(hadoop            2.7.3                                    )
# LCG_external_package(hbase             1.2.0                                    )
# LCG_external_package(hepdata_converter 0.1.23                                   )
# LCG_external_package(hepdata_validator 0.1.8                                    )
# LCG_external_package(HepPDT            2.06.01                                  )
# LCG_external_package(hdf5              1.8.18                                   )
# LCG_external_package(HeapDict          1.0.0                                    )
# # LCG_external_package(hive              1.1.1                                    )
# # LCG_external_package(hspy              1.6.4                                    )
# # LCG_external_package(h5py              2.6.0                                    )
# # LCG_external_package(html5lib          0.999999999                              )
# # LCG_external_package(idna              2.6                                      )
# # LCG_external_package(ipython           5.4.1                                    )
# # LCG_external_package(ipython_genutils  0.1.0                                    )
# # LCG_external_package(ipykernel         4.6.1                                    )
# # LCG_external_package(ipywidgets        5.2.2                                    )
# LCG_external_package(isort             4.3.3                                    )
# LCG_external_package(java              8u91                                     )
# LCG_external_package(jemalloc          4.1.0                                    )
# LCG_external_package(Jinja2            2.10                                    )
# LCG_external_package(jpype             0.6.2                                    )
# LCG_external_package(jsonschema        2.4.0                                    )
# LCG_external_package(jupyter           1.0.0                                    )
# LCG_external_package(jupyter_client    5.1.0                                    )
# LCG_external_package(jupyter_core      4.4.0                                    )
# LCG_external_package(jupyter_console   5.0.0                                    )
# LCG_external_package(jupyter_contrib_nbextensions 0.2.1                         )
# LCG_external_package(jupyter_contrib_core 0.3.0                                 )
# LCG_external_package(jupyter_nbextensions_configurator 0.2.2                    )
# LCG_external_package(keras             2.1.1                                    )
# LCG_external_package(lapack            3.5.0                                    )
# LCG_external_package(lazy_object_proxy 1.3.1                                    )
# LCG_external_package(lcov              1.9                                      )
# LCG_external_package(libaio            0.3.110-1                                )
# LCG_external_package(libgit2           0.27.0                                   )
# LCG_external_package(libsvm            2.86                                     )
# LCG_external_package(libxslt           1.1.28                                   )
# LCG_external_package(logilabcommon     1.0.1                                    )
# LCG_external_package(lxml              4.1.1                                      )
#
# LCG_external_package(m4                1.4.17                                   )
# LCG_external_package(m2crypto          0.25.1                                     )
# LCG_external_package(MarkupSafe        0.23                                     )
# LCG_external_package(maven             3.3.9                                    )
# LCG_external_package(metakernel        0.20.12                                  )
# LCG_external_package(markdown          2.6.11                                   )
# LCG_external_package(matplotlib        2.1.0                                    )
# LCG_external_package(mccabe            0.6.1                                    )
# LCG_external_package(messaging         1.0                                      )
# LCG_external_package(mistune           0.5.1                                    )
# LCG_external_package(mock              2.0.0                                    )
# LCG_external_package(mpfr              3.1.5                                    )
# LCG_external_package(mpfi              1.5.1                                    )
# LCG_external_package(mpich2            1.5                                      )
# LCG_external_package(mpmath            1.0.0                                    )
# LCG_external_package(msgpack           0.5.6                                    )
# LCG_external_package(multiprocess      0.70.4                                   )
# LCG_external_package(multiprocessing   2.6.2.1                                  )
# LCG_external_package(mysql_python      1.2.3                                    )
# LCG_external_package(nanomsg           1.1.3                                    )
# LCG_external_package(nbconvert         5.1.1                                    )
# LCG_external_package(nbformat          4.0.1                                    )
# LCG_external_package(networkx          1.11                                     )
# LCG_external_package(ninja             1.7.2.gcc0ea.kitware.dyndep              )
# LCG_external_package(nose              1.1.2                                    )
# LCG_external_package(notebook          4.2.1                                    )
# LCG_external_package(numexpr           2.6.4                                    )
# LCG_external_package(octave            4.2.1                                    )
# LCG_external_package(octavekernel      0.28.3                           )
#
# LCG_external_package(pacparser         1.3.5                                    )
# LCG_external_package(pandas            0.21.0                                   )
# LCG_external_package(pandocfilters     1.4.1                                    )
# LCG_external_package(pathlib2          2.1.0                                    )
# LCG_external_package(pathos            0.2.0                                    )
# LCG_external_package(patsy             0.4.1                                    )
# LCG_external_package(pbr               2.0.0                                    )
# LCG_external_package(pexpect           4.2.0                                    )
# LCG_external_package(pickleshare       0.7.2                                    )
# LCG_external_package(pip               9.0.1                                    )
# LCG_external_package(pjlsa             0.0.12                                   )
# LCG_external_package(pox               0.2.2                                    )
# LCG_external_package(ppft              1.6.4.6                                  )
# LCG_external_package(prctl             1.7                                  )
# LCG_external_package(prettytable       0.7.2                                    )
# LCG_external_package(processing        0.52                                     )
# LCG_external_package(prompt_toolkit    1.0.3                                    )
# LCG_external_package(protobuf          2.5.0                                    )
# LCG_external_package(ptyprocess        0.5.1                                    )
# LCG_external_package(psutil            4.3.1                                    )
# LCG_external_package(py                1.4.33                                    )
# LCG_external_package(py2neo            1.4.6                                    )
# LCG_external_package(py4j              0.10.3                                   )
# LCG_external_package(pyanalysis        2.0                                      )
# LCG_external_package(pydot             1.2.3                                    )
# LCG_external_package(pydot_ng          1.0.0                                    )
# LCG_external_package(pygments          2.0.2                                    )
# LCG_external_package(pygraphics        2.0                                      )
# if(NOT ${LCG_OS} MATCHES mac)
#   LCG_external_package(pygsi             0.6.3                                    )
# endif()
# LCG_external_package(pyjapc            1.4.1                                    )
# LCG_external_package(pylint            1.9.1                                    )
# LCG_external_package(pyparsing         2.1.8                                    )
# LCG_external_package(pyqt5             5.9.1                                    )
# LCG_external_package(pystan            2.16.0.0                                    )
# LCG_external_package(pytest            3.2.5                                    )
# LCG_external_package(pytimber          2.6.2                                   )
# LCG_external_package(pytz              2017.3                                   )
# # LCG_external_package(PythonFWK         2.7.13                                   )
# # LCG_external_package(python_dateutil   2.4.0                                    )
# # LCG_external_package(python_gitlab     0.20                                    )
# if(${LCG_OS} STREQUAL slc OR ${LCG_OS} STREQUAL centos OR ${LCG_OS} STREQUAL cc)
# LCG_external_package(pythonsollya      0.1                                     )
# endif()
# LCG_external_package(pytools           2.0                                      )
# LCG_external_package(PyHEADTAIL        1.12.1                                   )
# LCG_external_package(PyYAML            3.12                   pyyaml            )
# LCG_external_package(pyxml             0.8.4p1                                  )
# LCG_external_package(pyzmq             17.0.0b3                                   )
# LCG_external_package(QMtest            2.4.1                                    )
# ###LCG_external_package(Qt                4.8.7                     qt             )
# LCG_external_package(qtconsole         4.2.1                                    )
# ##LCG_external_package(qwt               6.0.1                                    )
# LCG_external_package(rangev3           0.3.0                                 )
# LCG_external_package(requests          2.18.4                                   )
# LCG_external_package(rootpy            0.8.1                                    )
# LCG_external_package(root_numpy        4.6.0                                    )
# LCG_external_package(rpy2              2.8.0                                    )
# LCG_external_package(singledispatch    3.4.0.3                                  )
# LCG_external_package(scikitlearn       0.18.1                                   )
# LCG_external_package(scipy             1.0.0                                   )
# LCG_external_package(seaborn           0.7.1                                    )
# LCG_external_package(simplegeneric     0.8.1                                    )
# LCG_external_package(simplejson        3.8.2                                    )
# LCG_external_package(sip               4.19.5                                   )
# LCG_external_package(six               1.10.0                                    )
# LCG_external_package(sollya            6.0                                      )
# ####LCG_external_package(soqt              1.5.0                                    )
# if(${LCG_OS} STREQUAL slc OR ${LCG_OS} STREQUAL centos)
#   LCG_external_package(spark             2.3.0                                    )
# endif()
# # LCG_external_package(sortedcontainers  2.0.2                                    )
# # LCG_external_package(sqlalchemy        1.1.15                                    )
# LCG_external_package(statsmodels       0.8.0                                    )
# LCG_external_package(stomppy           3.1.3                                    )
# LCG_external_package(storm             0.19                                     )
# LCG_external_package(subprocess32      3.2.6                                    )
# LCG_external_package(swig              3.0.12          author=3.0.12            )
# LCG_external_package(sympy             1.1.1                                    )
# LCG_external_package(tblib             1.3.2                                    )
# #LCG_external_package(tcmalloc          2.4                                      )
# LCG_external_package(tensorboard       1.8.0                                 )
# LCG_external_package(tensorflow        1.8.0                                    )
# LCG_external_package(terminado         0.5                                      )
# LCG_external_package(testpath          0.3.1                                    )
# LCG_external_package(texinfo           6.3                                      )
# LCG_external_package(theano            0.8.2                                    )
# LCG_external_package(toolz             0.9.0                                    )
# LCG_external_package(tornado           4.5.3                                    )
# LCG_external_package(traitlets         4.2.2                                    )
# LCG_external_package(tricktrack        1.0.2                                    )
# LCG_external_package(typing            3.5.2.2                                  )
# LCG_external_package(urllib3           1.22                                     )
# LCG_external_package(uuid              1.42                                     )
# if(NOT ${LCG_OS} STREQUAL mac)
#   LCG_external_package(valgrind          3.11.0                                   )
# endif()
# LCG_external_package(umesimd           0.8.1                                     )
# LCG_external_package(veccore           0.4.2                                      )
# LCG_external_package(vectorclass       1.30                                     )
# LCG_external_package(vdt               0.3.9                                    )
# LCG_external_package(wcwidth           0.1.7                                    )
# LCG_external_package(wheel             0.29.0                                   )
# LCG_external_package(webencodings      0.5.1                                    )
# LCG_external_package(werkzeug          0.14.1                                   )
# LCG_external_package(widgetsnbextension 1.2.6                                   )
# LCG_external_package(wrapt             1.10.11                                  )
# LCG_external_package(xapian            1.2.21                                   )
# LCG_external_package(xgboost           0.71                                     )
# LCG_external_package(xqilla            2.3.3                                    )
# LCG_external_package(xz                5.0.4                                    )
# if(NOT ${LCG_OS} STREQUAL mac)
#   LCG_external_package(xrootd_python     0.3.0                                    )
# endif()
# LCG_external_package(yamlcpp           0.5.1                                    )
# LCG_external_package(zeromq            4.1.6                                    )
# LCG_external_package(zict              0.1.3                                    )

#---Additional External packages------(Generators)-----------------
include(${CMAKE_CURRENT_LIST_DIR}/heptools-dev-generators.cmake)

# Prepare the search paths according to the versions above
LCG_prepare_paths()
