#!/bin/sh
# A simple wrapper for LCGCMake

case $1 in
  configure)
                /usr/bin/cmake3 -DCMAKE_INSTALL_PREFIX=/build/lcgcmake-install -DLCG_VERSION=hsf /build/lcgcmake
                ;;
  install)
                make -j24 $2
                ;;
  *)
esac
